management:
  endpoint:
    shutdown:
      enabled: true
    health:
      #show-details: always
      show-components: always
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true


info:
  app:
    name: oh-actuator
    company: oh
